owner-name: Sander van Zoest
owner-page: https://sander.vanzoest.com/
owner-email: sander+blog@vanzoest.com
server: false
lsi: false
markdown: kramdown
highlighter: rouge
#permalink: /:year/:month/:day/:title.html
permalink: /:year/:month/:title.html
paginate: 10
category_dir: topics
#category_title_prefix: 
exclude: ["lib", "blog.rb", "Capfile", "config", "log", "Rakefile", "tmp", "README.md", "LICENSE.md", "build", "test"]
